### ISSUE TITLE
Call of Duty Black Ops 2 not working on the latest nightly.

### ISSUE THREAD

**Issue by SHADOWG22** [dimok789/loadiine_gx2#137]
I was able to run Black Ops 2 on an earlier build, but was unable to boot into local multiplayer as n1ghty said was possible with the addition of cos.xml argstr arguments. I tried the latest build, but was greeted with a black screen. Any suggestions to fix this issue?

**Comment by CreeperMario** [comment]
Yes, actually. Revert to the older version.
But seriously, v0.3 is still being worked on. The nightly versions aren't suitable for general public use, these versions are mostly for testing.

Only a dev would have an answer to this... @dimok789 @dibas @Maschell @n1ghty any insight?

**Comment by dibas** [comment]
As far as I can see, code related to passing arguments to the game has not been touched.

Could you please show me how your argstr looks like? Did you try other modes like +zm? What happens if you use the original cos.xml? 

I currently can't test on a console, so it would be great if you could pin down the commit where things stopped working for you. Just iterate through the nightlies starting from the version that worked. Thanks!

**Comment by SHADOWG22** [comment]
I tried a different dump of the game and I was able to boot into local multiplayer! It is weird that my initial dump worked on an earlier build, but not the latest one, though. I guess this was not a bug after all.

**Comment by SHADOWG22** [comment]
The new dump worked on the latest nightly.

**Comment by dibas** [comment]
Thanks for your reply. I am closing this issue then.
