### ISSUE TITLE
Crash with black screen if log server is enabled but not running

### ISSUE THREAD

**Issue by Leseratte10** [dimok789/loadiine_gx2#8]
I accidentally left the "log server" setting enabled without having a running logging server and no games did start, they just all froze on a black screen. 

It took some time until I found out that I still had that setting enabled - would it be possible to display a warning when a log server is enabled but cannot be connected to?

**Comment by dimok789** [comment]
Well since the log server is only used once the game is launched its not possible. What can be done is changing the whole log to UDP and it would not block if you dont have the reicever open.

Maybe some other time....this is really not priority. Besides this is not a crash you get it just waits for the applications response.

**Comment by Leseratte10** [comment]
Couldn't Loadiine send like a ping packet to the log server port to check if it is running and disable it if it isn't? Or does Loadiine have no network access?

**Comment by dimok789** [comment]
Hmm, my opinion is that this is a debug option for advanced users. If the "advanced" user forgot it, its his own fault.

Anyway, I can offer you to make the timeout of the connection lower. Lets say 10s ? Then it will continue with the game. Making a ping to check a connection is overkill for this really unwanted feature. I planning to replace that crap as the server application is really not good.

**Comment by Leseratte10** [comment]
10s connection timeout would also be a good solution.
